In [38]:
import numpy as np
from matplotlib import pyplot as plt
from modules.preProcessData import makeXbar

In [39]:
X = np.array([147, 150, 153, 158, 163, 165, 168, 170, 173, 175, 178, 180, 183]).reshape((-1,1))
y = np.array([49, 50, 51,  54, 58, 59, 60, 62, 63, 64, 66, 67, 68]).reshape((-1,1))
print(X.shape, y.shape)

(13, 1) (13, 1)


In [40]:
XBar = makeXbar(X)
print(XBar[:3])

[[  1. 147.]
 [  1. 150.]
 [  1. 153.]]


In [41]:
XTestBar = makeXbar(np.array([158, 173, 190, 205]).reshape((-1,1)))

In [45]:
from modules.LapisLinearRegression import LapisLinearRegression

lapisLinearRegr = LapisLinearRegression()
lapisLinearRegr.fit(XBar, y)
lapisYTest = lapisLinearRegr.predict(XTestBar)
print(lapisYTest)
print('w=', lapisLinearRegr.coef_.T)

[[54.61897378]
 [63.00704821]
 [72.51353256]
 [80.90160699]]
w= [[-33.73541021   0.55920496]]


In [46]:
from sklearn.linear_model import LinearRegression
linearRegr = LinearRegression(fit_intercept=False)
linearRegr.fit(XBar, y)
sklearnLinearY = linearRegr.predict(XTestBar)
print(sklearnLinearY)
print('w=', linearRegr.coef_)

[[54.61897378]
 [63.00704821]
 [72.51353256]
 [80.90160699]]
w= [[-33.73541021   0.55920496]]


In [55]:
from sklearn.linear_model import Lasso
lassoLinearRegr = Lasso(alpha=0.001, normalize=True)
lassoLinearRegr.fit(X, y)
lassoLinearRegrYTest = lassoLinearRegr.predict(X)
print(lassoLinearRegrYTest)
print('w=', lassoLinearRegr.coef_)

[48.47394745 50.15059844 51.82724943 54.62166775 57.41608606 58.53385339
 60.21050438 61.32827171 63.0049227  64.12269002 65.79934101 66.91710834
 68.59375933]
w= [0.55888366]


C:\lapis\program_files\python39\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Lasso())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * np.sqrt(n_samples). 
  warnings.warn(


In [50]:
from sklearn.linear_model import Lars
larsLinearRegr = Lars(fit_intercept=False)
larsLinearRegr.fit(XBar, y)
larsLinearRegrYTest = larsLinearRegr.predict(XTestBar)
print(larsLinearRegrYTest)
print('w=', larsLinearRegr.coef_)

[54.61897378 63.00704821 72.51353256 80.90160699]
w= [-33.73541021   0.55920496]


C:\lapis\program_files\python39\lib\site-packages\sklearn\linear_model\_base.py:133: FutureWarning: The default of 'normalize' will be set to False in version 1.2 and deprecated in version 1.4.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Lars())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(
